services:
  image-simulation-to-synthetic-waveform-api:
    container_name: image-simulation-to-synthetic-waveform-api
    image: evdev3/image-simulation-to-synthetic-waveform-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env